### ISSUE TITLE
Cannot save new job if editor panel is used to create name

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#1001]
https://www.loom.com/share/410646fee7404be4b35e9c8a7c61c49a

**Comment by stuartc** [comment]
@taylordowns2000 this is a tough one.

The reason it's not saving is because the job has a nil body. The body is populated with a default only when the placeholder is accepted.

However the way we distinguish a placeholder from another job node is by checking for the existence of a name and body...

An intentional side effect of the syncing design is that it's really difficult to tell the difference between the client and server.

@josephjclark maybe I could get your advice here? I'm happy to keep the defaults in the front end (btw we _do_ inject the default adaptor in a sync response fwiw - maybe we move that to the FE as well). I think we need to track the placeholder in the components state rather than derive which node is a placeholder; but this feels like it could be a sticky/tedious rearrange of the `createNewWorkflow` and `identify` functions...

I think this catch 22 between having a default body (or any other attrs) from the start will go away if we can decide which node is a placeholder and track that internally.

**Comment by stuartc** [comment]
Notes from chat with @josephjclark 

1. Proposing we _don't_ send a placeholder job to the server
2. We show a disabled/empty form, that _doesn't_ update as you type the name into the placeholder - it's just a blank box with some info.
3. Using a `m=placeholder` query string to control showing this box.
4. You won't be able to edit a Job _until_ you commit the placeholder.
