### ISSUE TITLE
Fix regressions with RTM Implementation (tests)

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1213]
**Fix following tests:**
- [ ] Filtering work orders
- [x] Retrying work attempts (WIP: @midigofrank )
- [ ] Setup Utils
- [x] Workflow tests 

**Remove the following tests:**
- [ ] Oban manager tests
- [ ] Pipeline tests
- [ ] Invocation Reasons

- - -

There are a few comments on the outstanding release PR, https://github.com/OpenFn/Lightning/pull/1184 that outlines some of the changes and new preferred ways of generating test data.

We want to stop using our fixture modules and use the factories essentially everywhere.

**Comment by stuartc** [comment]
@Elias @Frank Midigo

I've just pushed a bunch of test changes, focussing on test/lightning_web/live/work_order_live_test.exs, and I've added some comments on Github on the commit:

https://github.com/OpenFn/Lightning/pull/1184/commits/788ce1ecfa464b73381e0254061ff9d2b931d663#

Please could you guys read my comments, and next week we can sync up and I'll answer and questions etc.

I need one or both of you guys to get the tests for test/lightning_web/live/work_order_live_test.exs passing.

I have noted the following issues (I'm sure there will be more):

** (RuntimeError) found duplicate ID "af3f605d-eee6-40d6-b1a6-f44a00d13e93" for component LightningWeb.RunLive.WorkOrderComponent when rendering template
It looks like the new query returns duplicate WorkOrders, probably the joins (:shrug: )?
** (Postgrex.Error) ERROR 23502 (not_null_violation) null value in column "dataclip_id" of relation "attempts" violates not-null constraint
You're going to see a lot of these, Attempts must have a dataclip, it's mostly the chore of changing the factories to the new preferred style I outlined in the Github comments mentioned above. 
I've hesitated to add a default dataclip to the factory for attempts, since there will be places where the dataclip must be associated with the same project and we can't easily reach "back up" and get the project when making the factory. And a lot of the time when making runs we want the first run to have the same dataclip as the attempt.
Not really an error, but this is important: we are going to deprecate Lightning.WorkOrderService shortly, there are new implementations of most (if not all) of the WorkOrder creation/retry/building functions in Lightning.WorkOrders. @midigofrank I'm sure you will be able to lend a hand here with the retries/bulk retries here.

So to round this off, I see two aspects to this work:

Get the factories/setup data cleaned up and using the newer patterns - also please remove any factory code that isn't actually used or needed; the test setups we have are super dense and we want to make them as clean as possible.
Find and report or fix regressions, with the file in question this will be around retries and searching I think.
This is going to be a pretty gnarly space to dig into, but I will try and help anyone getting involved as much as possible next week.

**Comment by taylordowns2000** [comment]
congrats @elias-ba and @midigofrank on all the hard work here
