### ISSUE TITLE
Improve UI when non-accessible users access project security settings

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1477]
Currently users that don't have access to the MFA page attached (assuming by role, this screenshot was created by an `Editor`) 

Possible solutions:
- Hide menu item for MFA on navigation and 404 if user tries to access it

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjRUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--146d90643b27ee3ca882b6aa5ff088e188760ddd/image.png)

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Thunderbolt--Lightning-6305f22ada44914905485ab1/issues/OpenFn/Lightning/1477?planning-poker) with Zenhub @benedictus-dev @elias-ba @jyeshe @midigofrank @stuartc

**Comment by taylordowns2000** [comment]
noting that we will make this page visible and make the button appropriately read-only for `viewer` or `editor` users soon @NickOpenFn

**Comment by taylordowns2000** [comment]
hey @midigofrank , i'm re-opening this because i had to revert one of your changes here: https://github.com/OpenFn/Lightning/pull/1591/files#diff-ab2038829f13be727c2f8f9dbb8507b687a5931dd1560c6739c60b02e5f0d834

please confirm that you've got everything you need to close #1477 despite me reverting this bit of code.
