### ISSUE TITLE
Critical: Newly created workflows are created with no trigger

### ISSUE THREAD

**Issue by NickOpenFn** [OpenFn/Lightning#1537]
**To reproduce:**
- log on to demo.openfn.org
- Create a new workflow

**Issues:**
- There will be nodes on the canvas
- The job panel will display, with no jobs

**Comment by stuartc** [comment]
Ok an update on this, it's a doozy. Something is getting in the way of LiveViews dom updating and the new changes after a Job is created are not actually on the dom, and so when you change selection it tries to remove those elements and an error is thrown.

So far it appears to be caused by the WorkflowEditor component pushing a url patch and the updates not being applied. If you comment out `pushHistoryPatch` call in `assets/js/workflow-editor/index.ts` the problem goes away - albeit you can't actually click on anything but the underlying symptom (of missing elements) goes away.
