### ISSUE TITLE
Optimize search on history page

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#1803]
Placeholder for the epic to "fix" or optimize search. Note:

1. We don't partition stuff by time right now.
2. We don't have the fancy GIN indexes (for jsonb) that we used in v1.
3. We _might_ be able to seriously improve performance here via indexes and careful query refactor before reaching for some big ole search solution.

- [x] #1898
- [x] #1939 

Related bugs:
- https://github.com/OpenFn/lightning/issues/1794
- https://github.com/OpenFn/lightning/issues/968

Related future enhancement: https://github.com/OpenFn/lightning/issues/981

Related issue: Depending on how we solve this search functionality, we might potentially have solution for the filtering use case.
https://github.com/OpenFn/lightning/issues/1791

**Comment by christad92** [comment]
#1794 DBConnection.ConnectionError is still persistent.

To test this, search for the "Register New Patient" on the search page and include inputs in the search. It returns an error message as shown in the image below. 



![Image](https://github.com/OpenFn/lightning/assets/5230530/507c8208-e12f-41fa-9068-d2fce11fd551)

**Comment by stuartc** [comment]
As stated in https://github.com/OpenFn/lightning/pull/1914, the indexes are not used by the queries yet. We need to discuss how we want to implement this because:

1. tsvector queries don't make sense to apply to a dataclip body currently
2. the new gin indexes on dataclips may not produce correct results with users entering a string of words.
  When searching structured data, for accurate and performant results a containment query should be provided. For example `{"foo": "bar"}`, becomes `WHERE body @> '{"foo": "bar"}'::jsonb`. Or we use JSONPath (`WHERE body@?'$.data.patientData ? (@.name == "Wally")`)
