### ISSUE TITLE
Make "Initiate Github Sync" take the latest snapshots at the time of initiation

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#1827]
When you "initiate a sync" to Github via the Project Settings screen, it should contain send the latest workflow snapshot for all workflows in the project and send those UUIDs to Github.

This will avoid "drift" between when the sync is initiated and when the `openfn pull` command actually grabs yaml from openfn.org

**Comment by christad92** [comment]
@taylordowns2000 I would like to propose that we have the  Save & Sync button on the canvas (probably beside the save button) rather than on the inspector page because :
- The inspector primary controls the current step; and
-  The existing buttons on the inspector (`Create New Work Order` and `Save`) function within the scope of that step.

**Comment by midigofrank** [comment]
Blocked, waiting for OpenFn/kit#729

**Comment by christad92** [comment]
[#729](https://github.com/OpenFn/kit/issues/729) has been merged.. Can you raise a PR for this, if it's ready? 

Thanks
