### ISSUE TITLE
Enable users to differentiate between staging and production credentials (2.4)

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#192]
As a user that collaborates with others on workflows,
I would like to be able to differentiate between staging and production credentials
So that my colleagues and I can more easily identify the credentials we would like and mix them up less often. 

When a user creates a credential, they should have a toggle button that makes them choose whether to mark the credential as staging or production. The toggle button should be set to 'staging' by default. 

- [x] add checkbox toggle to the CredentialForm component
- [x] display "production" on the credential view and list with the `HeroIcon.Outline.exclamation`
- [x] add a boolean ? column to the credentials table for `production`

**Comment by taylordowns2000** [comment]
@amberrignell , @stuartc , I'm caught in two minds here... part of me wants to limit this really severely, but the other wants to add a `:tags` column and then display those tags like in the image below

![Image](https://user-images.githubusercontent.com/8732845/180031830-531a4c07-c615-499f-8c08-399c00307de9.png)

Is the problem that users face really _just_ that they don't have a simple visual reminder that creds (and jobs using those jobs) are linked to "production" systems? If so, maybe this is a boolean rather than a picklist—it let's them effectively mark a credential (and in turn related jobs) as somehow 🚨 "dangerous" 🚨 or to-be-treated with extra caution.

**Comment by amberrignell** [comment]
@taylordowns2000  re:your comment here, not sure I understand what the tags would allow users to do / how much value it would bring. I'd agree with the checkbox approach.

**Comment by amberrignell** [comment]
all agree on the checkbox approach

**Comment by elias-ba** [comment]
@taylordowns2000 and @amberrignell did you agree on what to do ? I am picking this and the checklist clearly states that we should go with the toggle button. Is this confirmed ?

**Comment by taylordowns2000** [comment]
yes, @elias-ba , toggle. see task list in the issue description

**Comment by elias-ba** [comment]
Thanks @taylordowns2000
