### ISSUE TITLE
Purge a user's account, credentials data through the UI (3.1)

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#195]
As a Lightning user within an organisation that is leaving (or an administrator with a user that is leaving)
I would like to purge my account, credentials and workflow data
So that I can ensure any identifiable or sensitive information will be deleted

- [x] Add a 'purge data' action in the list of users on the `user_live` index page
- [x] Add a 'delete my account' action in the list of users on the `profile_live` page
- [x] For both delete pathways, displays a  confirmation modal (ask them to type out their username) and deletes `users`, `credentials` and `project_users` accordingly. (later, this could be extended to SHOW what will be deleted.)

See last comment for tests.

### Next issue

- [x] get_user_data returns a list of credentials that are owned by the user and projects that the user is in (any other identifiable data ?) to be deleted
- [x] when a user who has their account scheduled for deletion attempts to sign in, they are redirected to the "your account is scheduled for deletion" page

Deletion works as such: 
- project only has one user -> delete the project
- project has several users -> remove user from project users
- credential owned by user and not used anywhere -> delete credential
- credential owned by user but used in a workflow -> ask user to transfer ownership

**Comment by taylordowns2000** [comment]
- On openfn.org we've got a 7 day grace period where the account/project is not available but has been "marked for deletion".
- The user can reach out to the instance administrator to cancel the scheduled deletion.

This feels sensible, but would require either a `scheduled_deletion` column on the DB for each of these entities or a new mechanism... the mechanism could be a single future-scheduled deletion in Oban. The admin would then have 7 days to remove that work order from the `oban_jobs` table, or it would get picked up and handled by a deletion worker. This feels super clean, IMO.

**Comment by stuartc** [comment]
Considerations:

**Anonymize** parent records, in the case of a user being removed (user account "deletion"), we still need to keep records of that entity in the system for auditing.

So for a user that _may_ have created some jobs, and _may_ have some credentials in a project they are _not_ the owner of:

- All audit logs still need a user entity associated with them  
  I propose we randomise the first and last name, set the password to null, set the email to null, and mark the user as 'scrubbed' (or something similar). That way logs are still in tact but the user cannot be identified (at least in a GDPR context).
- Credentials can either be (user choice) be transferred (i.e. reject purging if they want to transfer them), or 'revoke' in which case jobs that use that credential will be marked as 'needing attention' and disabled as their credential will be deleted.

**Comment by amberrignell** [comment]
still some details to iron out, we'll need more time on this one

**Comment by elias-ba** [comment]
Hey I am starting on this. For now I am doing a very generic stuff, I am writing a `purge_user_data` function that will delete a lot of stuff in DB for that user. The idea is to start like that and the see how that function will help us in the next steps. So my questions are not blocking yet and may be wont be blocking until monday but I wanna make sure we are aligned on what to build as feature. What will be the DOD of this issue.

Questions:

- Are we finally implementing a 7 (or 8 or 10 or ...) days grace period for the user who wanna delete their stuff ? If yes, then I think we'll need Oban (which I am excited for).
- What are we doing with @stuartc's considerations [here](https://github.com/OpenFn/Lightning/issues/195#issuecomment-1191333373) ?
- Shouldn't we have a role transfer feature for when the admin want to delete his account ? What happens when an admin / superuser deletes their account ? All other accounts are going to be deleted ? Will we have an instance with no superuser ? Will we transfer the superuser to another user (I am think of a text input where they will type the email of the new superuser - before deleting their account) ?

These are the questions I have in top of my mind for now, but as I said they are not extremely urgent for now (at least for today)

**Comment by elias-ba** [comment]
Discussion led to the following conclusion. We're going to implement the same feature than in Platform. Here is the scenario:
1 - Have a button for the user to delete / purge their account / data.
2 - That button actually schedules an Oban job for deleting that users data.
3 - The Oban job will call a `purge_users_data(%User{id: user_id})` function
4 - The `purge_users_data` function is for now an `Enum` of SQL queries executed in order (for simplicity) but later on we'll turn it into an Ecto Transaction or Multi logic
5 - Two emails need to be sent to the user. One when deletion is planned (which will have instructions for canceling the deletion) and one when deletion is performed (which will have a goodbye message)

**Comment by taylordowns2000** [comment]
unit tests:

- [ ] after deletion is done, no artifacts owned by user remain via Repo.get(...)
- [ ] tbc...

live view feature tests:

- [ ] when a user clicks the "purge my account" button they see a confirmation modal asking if they really want to delete; clicking cancel does NOT delete anything.
- [ ] when a user clicks the "purge my account" button they are redirected to the "your account is scheduled for deletion" page
- [ ] when a user who has their account scheduled for deletion attempts to sign in, they are redirected to the "your account is scheduled for deletion" page
