### ISSUE TITLE
Remove `MainSection`

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#207]
- [x] migrate `lib/lightning_web/templates/user_session/new.html.heex` to the new `Layout` component
- [x] delete `alias Components.MainSection` from `lib/lightning_web.ex`
- [x] delete `lib/lightning_web/live/components/main_section.ex`

**Comment by elias-ba** [comment]
Hey @stuartc we are having some trouble with completing this issue. See my discussion with @taylordowns2000 below.

[Taylor](https://app.slack.com/team/U1B85TD9B)
hey 
[@Elias](https://openfn.slack.com/team/U02E698R5S8), is this still giving you trouble?


[Elias](https://app.slack.com/team/U02E698R5S8)
  [il y a 29 minutes](https://openfn.slack.com/archives/G2LJCFFDW/p1658417998739389?thread_ts=1658396529.492199&cid=G2LJCFFDW)
Yeah 
[@Taylor](https://openfn.slack.com/team/U1B85TD9B)
 I was about to ping you even


[Taylor](https://app.slack.com/team/U1B85TD9B)
:calendrier_spirale:  [il y a 29 minutes](https://openfn.slack.com/archives/G2LJCFFDW/p1658418038123089?thread_ts=1658396529.492199&cid=G2LJCFFDW)
darn! sorry dude.


[Taylor](https://app.slack.com/team/U1B85TD9B)
:calendrier_spirale:  [il y a 29 minutes](https://openfn.slack.com/archives/G2LJCFFDW/p1658418053963229?thread_ts=1658396529.492199&cid=G2LJCFFDW)
can you write up what you think the problem is and what you’ve tried to solve it here in slack?


[Elias](https://app.slack.com/team/U02E698R5S8)
  [il y a 27 minutes](https://openfn.slack.com/archives/G2LJCFFDW/p1658418121144339?thread_ts=1658396529.492199&cid=G2LJCFFDW)
Yeah I think the main problem is that we're not loading the login page the same way than the other pages. it makes sense because the login page came lately and is not served by liveview


[Elias](https://app.slack.com/team/U02E698R5S8)
  [il y a 27 minutes](https://openfn.slack.com/archives/G2LJCFFDW/p1658418145940389?thread_ts=1658396529.492199&cid=G2LJCFFDW)
So for some reason the global CSS or configs doesn't apply to it


[Elias](https://app.slack.com/team/U02E698R5S8)
  [il y a 27 minutes](https://openfn.slack.com/archives/G2LJCFFDW/p1658418176738629?thread_ts=1658396529.492199&cid=G2LJCFFDW)
So far I tried to play a little bit with changing the CSS in the Chrome inspector but nothing promising


[Elias](https://app.slack.com/team/U02E698R5S8)
  [il y a 26 minutes](https://openfn.slack.com/archives/G2LJCFFDW/p1658418207241799?thread_ts=1658396529.492199&cid=G2LJCFFDW)
I can't even draw distinctions (with border: 5px solid red) between the form, the divs and the body


[Elias](https://app.slack.com/team/U02E698R5S8)
  [il y a 25 minutes](https://openfn.slack.com/archives/G2LJCFFDW/p1658418248478049?thread_ts=1658396529.492199&cid=G2LJCFFDW)
But the most annoying is that we can cleary see that all the elements are rendering fine. Just as if there was a problem with the z-index or something like that


[Elias](https://app.slack.com/team/U02E698R5S8)
  [il y a 25 minutes](https://openfn.slack.com/archives/G2LJCFFDW/p1658418265952419?thread_ts=1658396529.492199&cid=G2LJCFFDW)
What do you think 
[@Taylor](https://openfn.slack.com/team/U1B85TD9B)
?


[Taylor](https://app.slack.com/team/U1B85TD9B)
:calendrier_spirale:  [il y a 25 minutes](https://openfn.slack.com/archives/G2LJCFFDW/p1658418291010269?thread_ts=1658396529.492199&cid=G2LJCFFDW)
tricky. is there a good reason that login isn’t a liveview?


[Elias](https://app.slack.com/team/U02E698R5S8)
  [il y a 24 minutes](https://openfn.slack.com/archives/G2LJCFFDW/p1658418337325859?thread_ts=1658396529.492199&cid=G2LJCFFDW)
No, the only reason is because at the time we were doing authentication we didn't know how to make liveview work with the auth library


[Elias](https://app.slack.com/team/U02E698R5S8)
  [il y a 23 minutes](https://openfn.slack.com/archives/G2LJCFFDW/p1658418384084249?thread_ts=1658396529.492199&cid=G2LJCFFDW)
I think, this is a good flag for having an issue around converting authentication / registration to a liveview component like all the other features of the app

**Comment by taylordowns2000** [comment]
@stuartc , the short is that the new `Layout` component doesn't work for login, and Elias suspects that there's a CSS-related issue that's hiding or badly z-indexing components since login isn't in liveview. When he migrated login to `Layout` (away from `MainSection`) his `:inner_section` disappears. it's "there", but it's not visible.
![image](https://user-images.githubusercontent.com/8732845/180264405-bc040c18-77d2-4490-b7ce-fe79b9ad38d0.png)

**Comment by stuartc** [comment]
@taylordowns2000 @elias-ba I've fixed the layout issue... The `app.html.heex` didn't have some surrounding blocks that are needed by the layout page_content blocks... 

These changes _can't_ go into the layout component as the flex orientation is different when you're logged out...

`app.html.heex`
```html
<main class="h-screen">
  <div class="flex flex-col h-full">  <!-- Note the flex-col -->
```

`live.html.heex`
```html
<main class="h-screen">
  <div class="flex flex-row h-full"> <!-- flex-row because of the left menu bar -->
```
