### ISSUE TITLE
Fix on-save validation/rejection for credentials

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/lightning#2099]
Attempting to save a credential with bad data no longer provides the user with a helpful message, after #1900 .

https://www.loom.com/share/4de7bc8e6014473d91e8a1f25c636b42

Should be fixed before we release `v2.5.0`

**Comment by elias-ba** [comment]
The solution to this problem seems much more expensive than the current budget. I spoke with @stuartc  and @christad92, and we all think it's better if I solve the most urgent issues first before coming back to this one. Perhaps by then, we will have thought of a much cheaper solution. Therefore, I am moving this ticket back to "Ready" and will take ticket #2101

**Comment by christad92** [comment]
We should consider a toast message that can be display the error when a user clicks save?
