### ISSUE TITLE
Scheduled deletion of users account does not work

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2500]
When user requests to delete their account, we have a grace period which is automatically set as the scheduled deletion date  for the account.  On the date, the account and every data associated with the account should be wiped off the database. 

This does not work at the moment - see table below for a list of deleted accounts, the records are still on the database even after the deletion period has passed. 

<img width="1418" alt="image" src="https://github.com/user-attachments/assets/8d169b0b-7c28-47d7-b515-838cda94a550">

The expected behaviour here is that the account is deleted as well as owned projects and credentials.

**Comment by taylordowns2000** [comment]
You may already know this (sorry if I'm off base!) but note that these won't be deleted if there is any associated history. (I think it explains this in the deletion notification email too!)

Since we don't enforce history retention limits, it's possible that these accounts will be preserved until all related activity history is purged, and they will _only then_ be deleted.

**Comment by midigofrank** [comment]
@taylordowns2000 good point. I have checked and the only history being checked before deletion is `run creation`

I have been able to test this with demo data. `viewer@openfn.org` gets deleted, `demo@openfn.org` (which I used to create runs) doesn't.

**Comment by midigofrank** [comment]
I've confirmed with @christad92 that the listed users don't have runs associated with them. There were some `audit_events` though.
Weirdly, in the dev db there is no fk constraint linking them to the `users`, therefore the users should just get deleted without any errors. 

Also if there are such errors (you cant delete because it is linked in x), shouldn't they get reported to sentry? 🤔

**Comment by christad92** [comment]
@midigofrank we have validated that scheduled deletion is blocked by Thunderbolt's fk constraint. Is there any thing else stopping this?

**Comment by midigofrank** [comment]
Yes, the problem is how do we handle the deletion in Thunderbolt?

What if the user is the billing account owner?

What of the billing account?

**Comment by christad92** [comment]
Thanks @midigofrank here is the note from our chat. 
![Image](https://github.com/user-attachments/assets/278e7b4c-794d-47df-bd73-9620b7dd05af)
