### ISSUE TITLE
App says I have the workflow opened in two tabs when I actually have only one tab opened

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2647]
![Image](https://github.com/user-attachments/assets/1382550e-6cd0-4618-8945-9330b71b2d5e)

This often happens when the user has a poor connection and refreshes the app. There seems to be a latency where LiveView does not realize that the previous connection has been terminated. 

_edit: (adding replication instructions)_

Replication instructions:
1. open workflow on computer/phone A
2. disable internet connection on computer/phone A
3. open workflow on computer/phone B
4. note warning
5. wait
6. refresh
7. note warning is gone (now that it realizes that the connection from A is dead)

**Comment by elias-ba** [comment]
The issue occurs because the app maintains the connection for 60 seconds when a user loses internet connectivity. During this time, users still see the "workflow open in 2 tabs" banner and cannot regain edit access, even if the second tab is no longer relevant (e.g., when the user disconnects their mobile device). This happens because we’ve configured a global 60-second timeout to allow users time to restore their connectivity without losing track of their work.

After reviewing the situation, we’ve decided to keep the 60-second timeout. Reducing it could potentially lead to unintended side effects, especially for users with unreliable connections, and may impact other areas of the app.

In this scenario, users will need to wait up to 60 seconds for the banner to disappear. Once the timeout has passed, they will automatically regain edit access on their second device. We understand that this can feel like a delay, but this behavior ensures a consistent experience for all users, particularly in cases of temporary connection issues.

**Comment by christad92** [comment]
> The issue occurs because the app maintains the connection for 60 seconds when a user loses internet connectivity. During this time, users still see the "workflow open in 2 tabs" banner and cannot regain edit access, even if the second tab is no longer relevant (e.g., when the user disconnects their mobile device). This happens because we’ve configured a global 60-second timeout to allow users time to restore their connectivity without losing track of their work.
> 
> After reviewing the situation, we’ve decided to keep the 60-second timeout. Reducing it could potentially lead to unintended side effects, especially for users with unreliable connections, and may impact other areas of the app.
> 
> In this scenario, users will need to wait up to 60 seconds for the banner to disappear. Once the timeout has passed, they will automatically regain edit access on their second device. We understand that this can feel like a delay, but this behavior ensures a consistent experience for all users, particularly in cases of temporary connection issues.

@elias-ba do we want to update the information in the banner to ask the user to refresh after 60 secs?

**Comment by elias-ba** [comment]
@christad92 they don't even need to refresh. They just need to wait. Maybe we should update the information in the banner and say that this may disappear in 60 seconds, I am not sure. cc @stuartc @taylordowns2000 @aleksa-krolls
