### ISSUE TITLE
Don't block editing when ONLY one workflow tab of N opened by the same user is latest

### ISSUE THREAD

**Issue by christad92** [OpenFn/lightning#2779]
Blocking workflow editing when a workflow is opened by a user on two or more tabs should ONLY happen if ONLY ONE tab of N opened tabs (of the workflow) is the latest version and the others are old snapshots.  

Please note that a user with edit privileges viewing old snapshots of a workflow is still a priority user and will block others from editing the workflow until they close the workflow.

**Comment by josephjclark** [comment]
This issue turns out to be a user error

I was opening the logs from Inspect This Step in the history page. This opened the inspector on the latest version for two different runs (so that I could compare). But they were the same version, not snapshots. It's quite correct for it to lock me out.

I should have clicked the the workflow name in the run histpry to open up the run view, which would have shown me logs without the Inspector. THIS was the UX I wanted.

Closing this as a wontfix. Thanks for investigating @elias-ba !
