### ISSUE TITLE
Issue with db connection when pool size isn't big enough

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#332]
**Describe the bug** 

When you run mix test, a random number of tests fails due to "_connection not available and request was dropped from queue after xxx ms_" xxx > 100 ms.  

The reason invoked each time: reason: :**queue_timeout**, severity: :error

**To Reproduce**

Local system: Ubuntu 22.04  32 GB CPU @2,60 GHz x 12

1. Check pool size = 10 in the test.exs
2. Run mix test
3. x tests / 356 tests  failed with the above error (x is random)

**Expected behavior** 

356 passing tests without exception

**Screenshots** 

**Additional context** 

When i raise the pool size from 10 to 15, all tests pass

**Comment by wanecode** [comment]
**Describe the bug** 

When you run mix test, a random number of tests fails due to "_connection not available and request was dropped from queue after xxx ms_" xxx > 100 ms.  

The reason invoked each time: reason: :**queue_timeout**, severity: :error

**To Reproduce**

Local system: Ubuntu 22.04  32 GB CPU @2,60 GHz x 12


1. Check pool size = 10 in the test.exs

**Expected behavior** A clear and concise description of what you expected to
happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Additional context** Add any other context about the problem here.

**Comment by stuartc** [comment]
@wanecode, if you run your tests with this: `MIX_ENV=test elixir --erl "+S 1" -S mix test` and with your pool at 10, what is the result?

**Comment by wanecode** [comment]
> @wanecode, if you run your tests with this: `MIX_ENV=test elixir --erl "+S 1" -S mix test` and with your pool at 10, what is the result?

They all pass ! 356 / 356

**Comment by stuartc** [comment]
So that command/argument limits the concurrency of the BEAM, so my theory is, your machine is going 'more parallel' than there are db connections.

I'm curious as I have a 12/24 CPU but running at 4.7Ghz and I don't get any timeouts.
Are you running one of the new Intel processors with the big small topology (12th gen I think)?

I guess I'd also like to know if you run the command with `+S 12` and `+S 8`.

Either way I'm happy to increase the pool size to 15 but only in `test.exs`.

**Comment by wanecode** [comment]
It' s a 9th gen Intel core I7

**Comment by wanecode** [comment]
+S 8 is ok

**Comment by stuartc** [comment]
The default is exactly how many core your OS presents, so in your case would be probably be 12.

I found this: https://www.erlang.org/doc/man/erl.html#+S

also you can verify (kinda) what Erlang thinks should be the number of schedulers like this:

```
$ elixir --version
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:32:24] [ds:32:24:10] [async-threads:1] [jit]
```
What does yours say?
Not quite sure what each number means, but in my case I do expect to see 24 somewhere.

It is odd that mine doesn't fail, but it could be (like only just maybe) that if you have a laptop that the core clocks could be dropping significantly with an all core load...

**Comment by stuartc** [comment]
Can you make a PR for the change to test.exs and reference this issue?

Your machine is far from slow, but in other situations we might want to change the queue timeout from 100ms to say 200ms - since that will be affected significantly by slower SSDs and machines with lower clocks.

**Comment by wanecode** [comment]
This is mine
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

**Comment by wanecode** [comment]
> Can you make a PR for the change to test.exs and reference this issue?
> 
> Your machine is far from slow, but in other situations we might want to change the queue timeout from 100ms to say 200ms - since that will be affected significantly by slower SSDs and machines with lower clocks.

Yes. Will do it now
