### ISSUE TITLE
Make job inspector a panel, not a pop-up

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Lightning#380]
The current job inspector appears in a popup on the right side of the screen. (See first image.)

Make it appear in a panel, not a pop-up. (See second image.) The panel should behave like the inspector on chrome.

It should be draggable and the contents _inside_ the panel (i.e., the form) should take up 100% of the panel. It should _not_ extend above the top menu, but rather sit inside the parent component which contains the top menu for user login, etc.

Note that this issue does _not_ involve styling for the job form, or making any changes to the job form. It's focused on the div that contains the job form.

While CSS and JS will be involved, your implementation should focus on functionality, not cosmetics.

## Implementation notes:
1. From @stuartc : "The changes required are to stretch the div to the bottom of the page (make is absolute positioning), and to resize it when the window/viewport is resized."
2. More from @stuartc: "Should the content of the panel require scrolling (i.e. viewport is small) then the scrolling must happen inside the panel, and should not affect the elements outside of it.. i.e. when scrolling past the end of the panel it should not scroll the diagram." - https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior
3. Possible helpful example for draggable: https://stackoverflow.com/questions/68446571/how-to-do-a-draggable-expandlble-div-react-tailwind
4. A thought from Stu on why we think making this div appear "on top" of the canvas rather than "side by side" with the canvas: "having the panel be on top in this specific case gives us the opportunity to refocus the diagram without it reacting to a container size change without us saying so... if however we still want to resize the diagram we will already have the places to control that with our callbacks for viewport resizes for the panel."

## Current

 ![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/ff35135c-3cd5-44a9-bf56-8122d22dc32d)

## Desired

![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/266a9740-5b27-4ca8-85bc-b661f021e04d)

**Comment by mtuchi** [comment]
I have made some progress styling the ` + New Job` panel, latest changes are on this PR #387 ( **⚠️  DO NOT MERGE**), branch `380_job_inspector_panel`, I will pick this up tomorrow. 
cc @stuartc @taylordowns2000 
![Screenshot from 2022-10-26 19-00-43](https://user-images.githubusercontent.com/6592749/198076570-e4900f57-d0bd-4416-a833-9844c68b4b05.png)

**Comment by mtuchi** [comment]
I have pushed my latest changes, the PR ( #387 ) is ready for review @stuartc
- [x] From @stuartc : "The changes required are to stretch the div to the bottom of the page (make is absolute positioning), and to resize it when the window/viewport is resized."
- [x] More from @stuartc: "Should the content of the panel require scrolling (i.e. viewport is small) then the scrolling must happen inside the panel, and should not affect the elements outside of it.
- [ ] Draggable (I have added the draggable icon on the side of the panel when creating a new job, but it's missing `js` to work as expected) @stuartc do we still need draggable?
- [x] A thought from Stu on why we think making this div appear "on top" of the canvas rather than "side by side" with the canvas: "having the panel be on top in this specific case gives us the opportunity to refocus the diagram without it reacting to a container size change without us saying so... if however we still want to resize the diagram we will already have the places to control that with our callbacks for viewport resizes for the panel."
