### ISSUE TITLE
Copy webhook url gives incorrect url

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#427]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior** A clear and concise description of what you expected to
happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Additional context** Add any other context about the problem here.

**Comment by stuartc** [comment]
@amberrignell given our discussion earlier today - I propose that the webhook url _should_ point at the trigger; I have a tiny change that makes the webhook controller find the job via the trigger id instead of the job id.

That is technically a breaking change - so I can make it backwards compatible but I don't think we need to support the previous way right?
