### ISSUE TITLE
Prevent user from registering if they haven't selected checkbox

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#531]
### User story
As OpenFn, I would like to prevent users from registering if they have not check the lightning beta checkbox, so that I ensure they have read the notice. 

### Details
Disable the checkbox by default. If the user hasn't selected it, prevent them from registering.

**Comment by josephjclark** [comment]
A few notes here from the CLI perspective:

1) You probably want `info` level logging, which takes most of the verbosity out but still gives you a good level of output. Passing `--log info` to the CLI would be a really quick fix if verbosity is a big problem (and I can see why it would be!)
2) The current CLI  (since `0.0.23`) will log node, CLI, runtime and compiler versions at `info` level. Adaptors is a little harder (but I'm working on it!)
3) I've implemented a JSON logger which logs all outputs as json objects like `{ level: 'info', name: 'job', message: 'hello world' }`. This will make it MUCH easier for Lightning to filter and nicely render the logs. That's not released yet but won't be far away.

**Comment by josephjclark** [comment]
Just to say that JSON logging is now available as of CLI 0.0.28, so work to add a client-side filter (i'd start with a simple Important/Everything switch) is now unblocked (CC @amberrignell)
