### ISSUE TITLE
Metadata not refreshing when credential is updated

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/Lightning#791]
**Describe the bug** 
When I update a credential and click save,  the metadata doesn't get updated. 

**To Reproduce**

1. Go to a job and edit the credential
2. Click on save
3. See metadata doesn't get updated (ex: if you didn't have a credential before, then you add one and click save you still see the no_credential error)

**Expected behavior** 
The metadata should be refreshed. 

**Additional context**
we’d like a way for the metadata component to detect a change to the credential, as users can now save the job inspector form with a new credential without the form closing

**Comment by josephjclark** [comment]
This is full of bees :(

**1. CLI Bug**

First off, the metadata needs to update when the credential OR adaptor changes.

And adaptor changes don't work right now because of https://github.com/OpenFn/kit/issues/215.

Luckily that one looks to be an easy fix and I'm going to go off and do this now.

**2. Change notification**

Secondly, the JobEditor component needs to know when the adaptor or credential has changed.

As it happens we get an event when the adaptor changes, but not the credential. Best I can do right now is to re-request metadata on every change, which feels, ah, suboptimal. 

If we could pass the credential name to the JobEditor, that would probably suffice for notification. It wouldn't help us if you go into the credential, change and save it though - because the name is the same. You'll have to close and re-open the panel to see the change.

I need help with this bit.

**3. Unsaved Changes**

This one is actually fine but just to articulate this fully: the metadata should update _before_ you hit save.

The Metadata Service rather smartly uses the changeset, so it WILL use unsaved changes to generate the metadata, so you should see changes immediately reflected in the form (I've proven this in a terrible test demo)

Which begs the question of when that unsaved changeset is lost....

**Comment by josephjclark** [comment]
The CLI issue (1) has been resolved (just need to update CLI version in lightning).

So what's left is to pass the credential name/id down to the component (2), which can trigger an update. That gets us out of the woods for the 80%.

The third issue is a bit of a by-the-way. If it isn't under control it needs spinning out into its own thing.

I'm gonna add a low estimate for that last task.
