### ISSUE TITLE
Show that the jobs' body is invalid

### ISSUE THREAD

**Issue by stuartc** [OpenFn/Lightning#957]
Currently we have no UX/UI hints that a Job's body is invalid.
At the moment, the only invalid state that exists is when the body for the code editor is empty.

In future, we will have another story expanding this for other error states.

## Technical Notes

Unlike #956 this button exists in LiveView.

Lets not change the Ecto model validation messages: i.e. "body can't be blank".
But rather use the `.errors` struct and it's metadata to determine if the validation failure for `body` is from a `validate_required` etc.

**Comment by osinga** [comment]
We're looking for two changes here:

1. **Add an error label next to the "Save" button in the editor modal**
  This is for immediate feedback when you try and save your changes.
  
  ![Canvas](https://github.com/OpenFn/Lightning/assets/6756723/07b06456-018c-4125-922d-205eb5f41490)

2. **Add an error label next to the editor button in the job settings modal**
  This is for when you've gone out of the editor modal while still in an invalid state. Otherwise you might run into the situation where we indicate the presence of an invalid node (https://github.com/OpenFn/Lightning/issues/956) but you can't see what's actually invalid.

  ![Canvas-2](https://github.com/OpenFn/Lightning/assets/6756723/d7dfcd3c-7b74-4e9b-8d96-7e17ca259e94)

**Comment by NickOpenFn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Engineering-6305f22ada44914905485ab1/issues/OpenFn/Lightning/957?planning-poker) with Zenhub @elias-ba @stuartc @zacck
